#!/bin/bash

echo "🧪 TESTING FRONTEND FUNCTIONALITY"
echo "================================="
echo ""

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Test current state
echo -e "${BLUE}📊 Current System State:${NC}"
echo "User count:"
dfx canister call social_network_backend debug_user_count

echo ""
echo "Sarv29's user details:"
dfx canister call social_network_backend get_user '(principal "stvk2-n25v2-ysxdx-ztgta-bnfe4-nacg4-o72xd-3lwyr-i3mck-vzi22-6qe")'

echo ""
echo "All posts count:"
dfx canister call social_network_backend get_all_posts | head -5

echo ""
echo -e "${YELLOW}🌐 Frontend Testing Instructions:${NC}"
echo "================================="
echo ""
echo "1. Open: http://be2us-64aaa-aaaaa-qaabq-cai.localhost:4943/"
echo "2. Should automatically login as Sarv29 (principal: stvk2-n25v2-ysxdx-ztgta-bnfe4-nacg4-o72xd-3lwyr-i3mck-vzi22-6qe)"
echo "3. Should show main app with navigation"
echo ""
echo -e "${BLUE}🧪 Test Cases to Verify:${NC}"
echo ""
echo "✅ AUTHENTICATION:"
echo "   - Should login automatically and show main app"
echo "   - Should show username 'Sarv29' in profile"
echo "   - Should show navigation: Home, Discover, Create, Profile, Logout"
echo ""
echo "✅ POST CREATION:"
echo "   - Click 'Create' button"
echo "   - Write a test post: 'Testing from Sarv29! Authenticated actor should work now 🚀'"
echo "   - Add hashtags: #test #sarv29 #authenticated"
echo "   - Click 'Create Post'"
echo "   - Should show success message and navigate to feed"
echo "   - Should see the new post in the feed"
echo ""
echo "✅ POST INTERACTIONS:"
echo "   - Should be able to like/unlike posts"
echo "   - Should be able to comment on posts"
echo "   - Should be able to share posts"
echo "   - Should see updated counts"
echo ""
echo "✅ PROFILE EDITING:"
echo "   - Click 'Profile' button"
echo "   - Click 'Edit Profile'"
echo "   - Update bio: 'Updated bio from authenticated Sarv29!'"
echo "   - Click 'Save Changes'"
echo "   - Should see updated profile"
echo ""
echo "✅ USER DISCOVERY:"
echo "   - Click 'Discover' button"
echo "   - Should see list of all users"
echo "   - Should be able to follow/unfollow users"
echo ""
echo -e "${RED}❌ Expected Issues (if not fixed):${NC}"
echo "   - 404 errors when trying to like/comment/share"
echo "   - 'User is not registered' errors"
echo "   - Posts not being created"
echo "   - Profile updates not working"
echo ""
echo -e "${GREEN}🔧 Debugging Steps:${NC}"
echo "1. Open browser developer tools (F12)"
echo "2. Check Console tab for errors"
echo "3. Look for these log messages:"
echo "   - '🔧 Authenticated actor created successfully'"
echo "   - 'Using actor: authenticated' (not 'anonymous')"
echo "   - No 404 errors on backend calls"
echo ""
echo -e "${YELLOW}📋 Backend Verification Commands:${NC}"
echo ""
echo "# Check if Sarv29 can create posts (should work):"
echo "dfx canister call social_network_backend create_post '(\"Test from backend as Sarv29\", vec {\"#backend\"}, vec {})' --identity sarv29_test"
echo ""
echo "# Check posts created by Sarv29:"
echo "dfx canister call social_network_backend get_user_posts '(principal \"stvk2-n25v2-ysxdx-ztgta-bnfe4-nacg4-o72xd-3lwyr-i3mck-vzi22-6qe\")'"
echo ""
echo "# Check if Sarv29 can like a post:"
echo "dfx canister call social_network_backend like_post '(1)' --identity sarv29_test"
echo ""
echo -e "${BLUE}🎯 Success Criteria:${NC}"
echo "✅ No 404 errors in browser console"
echo "✅ All social features work (post, like, comment, follow)"
echo "✅ Profile editing works"
echo "✅ User can create and see their own posts"
echo "✅ User can interact with other users' posts"
echo ""
echo -e "${GREEN}🚀 Ready for testing!${NC}"
echo "Open the browser and test all functionality."
echo "Report any errors or issues found."
